#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me 
# is redirecting to another page.

sudo su <<EOF
apt update
apt install nginx
service nginx start
sed -i '/server_name _;/a\
        location /redirect_me {\\
                return 301 https://youtu.be/B9LYL5OO7eQ?si=Z0UqqX7R97tM-7Gi;\\
        }' /etc/nginx/sites-available/default
service nginx restart
EOF
