#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me 
# is redirecting to another page.

sudo su <<EOF
apt update
apt install nginx
sed -i '/server_name _;/a\
        location /redirect_me {\\
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\
        }' /etc/nginx/sites-available/default
service nginx restart
EOF
