#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me 
# is redirecting to another page.

sudo apt-get update
sudo apt-get install -y nginx
sudo su <<EOF
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i '/server_name _/a\\
	error_page 404 /custom_404.html;\\
        location /redirect_me {\\
		return 301 https://youtu.be/B9LYL5OO7eQ?si=Z0UqqX7R97tM-7Gi;\\
        }\\
        location  /custom_404.html {\\
        	internal;\\
	}' /etc/nginx/sites-available/default
EOF
sudo service nginx start
