#!/usr/bin/env bash
# listening on port 80 of all the servers active IPv4 IPs
sudo su <<EOF
apt-get purge nginx
apt-get install nginx -y
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
EOF
