#!/usr/bin/env bash
# listening on port 80 of all the servers active IPv4 IPs
sudo sed -i 's/[[:space:]]listen 8[0-9]*;?/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart
pkill -o nginx
