#!/usr/bin/env bash
# Displays Best School 10 times
i=1
while  (( i <  11 ))
do
case $i in
((i == 4)))
        echo "bad luck"
;;

((i == 8)))
        echo "good luck"
;;

*)
        echo "Best School"
;;

((i++))

done
