#!/usr/bin/env bash
# Displays Best School 10 times
i=1
while  (( i <  21 ))
do

if [ "$i" -eq 4 ]
then
        echo "bad luck from China"

elif [ "$i" -eq 9 ]
then
        echo "bad luck from Japan"

elif [ "$i" -eq 17 ]
then
	echo "bad luck from Italy"
else
        echo "Best School"

fi

((i++))

done
