#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
sudo sed -i 's/www-data/nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
